package cn.com.lxsoft.bdasphone.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.com.lxsoft.bdasphone.entity.DanWei;
import cn.com.lxsoft.bdasphone.entity.LuXian;
import cn.com.lxsoft.bdasphone.entity.QiaoLiang;
import cn.com.lxsoft.bdasphone.entity.User;
import cn.com.lxsoft.bdasphone.entity.Patrol;
import cn.com.lxsoft.bdasphone.entity.Chart;
import cn.com.lxsoft.bdasphone.entity.Check;
import cn.com.lxsoft.bdasphone.entity.Dectect;
import cn.com.lxsoft.bdasphone.entity.BridgeJCSB;
import cn.com.lxsoft.bdasphone.entity.SearchHistory;
import cn.com.lxsoft.bdasphone.entity.Construct;
import cn.com.lxsoft.bdasphone.entity.Disease;
import cn.com.lxsoft.bdasphone.entity.YearTest;

import cn.com.lxsoft.bdasphone.database.greendao.DanWeiDao;
import cn.com.lxsoft.bdasphone.database.greendao.LuXianDao;
import cn.com.lxsoft.bdasphone.database.greendao.QiaoLiangDao;
import cn.com.lxsoft.bdasphone.database.greendao.UserDao;
import cn.com.lxsoft.bdasphone.database.greendao.PatrolDao;
import cn.com.lxsoft.bdasphone.database.greendao.ChartDao;
import cn.com.lxsoft.bdasphone.database.greendao.CheckDao;
import cn.com.lxsoft.bdasphone.database.greendao.DectectDao;
import cn.com.lxsoft.bdasphone.database.greendao.BridgeJCSBDao;
import cn.com.lxsoft.bdasphone.database.greendao.SearchHistoryDao;
import cn.com.lxsoft.bdasphone.database.greendao.ConstructDao;
import cn.com.lxsoft.bdasphone.database.greendao.DiseaseDao;
import cn.com.lxsoft.bdasphone.database.greendao.YearTestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig danWeiDaoConfig;
    private final DaoConfig luXianDaoConfig;
    private final DaoConfig qiaoLiangDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig patrolDaoConfig;
    private final DaoConfig chartDaoConfig;
    private final DaoConfig checkDaoConfig;
    private final DaoConfig dectectDaoConfig;
    private final DaoConfig bridgeJCSBDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig constructDaoConfig;
    private final DaoConfig diseaseDaoConfig;
    private final DaoConfig yearTestDaoConfig;

    private final DanWeiDao danWeiDao;
    private final LuXianDao luXianDao;
    private final QiaoLiangDao qiaoLiangDao;
    private final UserDao userDao;
    private final PatrolDao patrolDao;
    private final ChartDao chartDao;
    private final CheckDao checkDao;
    private final DectectDao dectectDao;
    private final BridgeJCSBDao bridgeJCSBDao;
    private final SearchHistoryDao searchHistoryDao;
    private final ConstructDao constructDao;
    private final DiseaseDao diseaseDao;
    private final YearTestDao yearTestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        danWeiDaoConfig = daoConfigMap.get(DanWeiDao.class).clone();
        danWeiDaoConfig.initIdentityScope(type);

        luXianDaoConfig = daoConfigMap.get(LuXianDao.class).clone();
        luXianDaoConfig.initIdentityScope(type);

        qiaoLiangDaoConfig = daoConfigMap.get(QiaoLiangDao.class).clone();
        qiaoLiangDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        patrolDaoConfig = daoConfigMap.get(PatrolDao.class).clone();
        patrolDaoConfig.initIdentityScope(type);

        chartDaoConfig = daoConfigMap.get(ChartDao.class).clone();
        chartDaoConfig.initIdentityScope(type);

        checkDaoConfig = daoConfigMap.get(CheckDao.class).clone();
        checkDaoConfig.initIdentityScope(type);

        dectectDaoConfig = daoConfigMap.get(DectectDao.class).clone();
        dectectDaoConfig.initIdentityScope(type);

        bridgeJCSBDaoConfig = daoConfigMap.get(BridgeJCSBDao.class).clone();
        bridgeJCSBDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        constructDaoConfig = daoConfigMap.get(ConstructDao.class).clone();
        constructDaoConfig.initIdentityScope(type);

        diseaseDaoConfig = daoConfigMap.get(DiseaseDao.class).clone();
        diseaseDaoConfig.initIdentityScope(type);

        yearTestDaoConfig = daoConfigMap.get(YearTestDao.class).clone();
        yearTestDaoConfig.initIdentityScope(type);

        danWeiDao = new DanWeiDao(danWeiDaoConfig, this);
        luXianDao = new LuXianDao(luXianDaoConfig, this);
        qiaoLiangDao = new QiaoLiangDao(qiaoLiangDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        patrolDao = new PatrolDao(patrolDaoConfig, this);
        chartDao = new ChartDao(chartDaoConfig, this);
        checkDao = new CheckDao(checkDaoConfig, this);
        dectectDao = new DectectDao(dectectDaoConfig, this);
        bridgeJCSBDao = new BridgeJCSBDao(bridgeJCSBDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        constructDao = new ConstructDao(constructDaoConfig, this);
        diseaseDao = new DiseaseDao(diseaseDaoConfig, this);
        yearTestDao = new YearTestDao(yearTestDaoConfig, this);

        registerDao(DanWei.class, danWeiDao);
        registerDao(LuXian.class, luXianDao);
        registerDao(QiaoLiang.class, qiaoLiangDao);
        registerDao(User.class, userDao);
        registerDao(Patrol.class, patrolDao);
        registerDao(Chart.class, chartDao);
        registerDao(Check.class, checkDao);
        registerDao(Dectect.class, dectectDao);
        registerDao(BridgeJCSB.class, bridgeJCSBDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(Construct.class, constructDao);
        registerDao(Disease.class, diseaseDao);
        registerDao(YearTest.class, yearTestDao);
    }
    
    public void clear() {
        danWeiDaoConfig.clearIdentityScope();
        luXianDaoConfig.clearIdentityScope();
        qiaoLiangDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        patrolDaoConfig.clearIdentityScope();
        chartDaoConfig.clearIdentityScope();
        checkDaoConfig.clearIdentityScope();
        dectectDaoConfig.clearIdentityScope();
        bridgeJCSBDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        constructDaoConfig.clearIdentityScope();
        diseaseDaoConfig.clearIdentityScope();
        yearTestDaoConfig.clearIdentityScope();
    }

    public DanWeiDao getDanWeiDao() {
        return danWeiDao;
    }

    public LuXianDao getLuXianDao() {
        return luXianDao;
    }

    public QiaoLiangDao getQiaoLiangDao() {
        return qiaoLiangDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PatrolDao getPatrolDao() {
        return patrolDao;
    }

    public ChartDao getChartDao() {
        return chartDao;
    }

    public CheckDao getCheckDao() {
        return checkDao;
    }

    public DectectDao getDectectDao() {
        return dectectDao;
    }

    public BridgeJCSBDao getBridgeJCSBDao() {
        return bridgeJCSBDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public ConstructDao getConstructDao() {
        return constructDao;
    }

    public DiseaseDao getDiseaseDao() {
        return diseaseDao;
    }

    public YearTestDao getYearTestDao() {
        return yearTestDao;
    }

}
