package cn.com.lxsoft.bdasphone.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.com.lxsoft.bdasphone.entity.DanWei;
import cn.com.lxsoft.bdasphone.entity.LuXian;
import cn.com.lxsoft.bdasphone.entity.QiaoLiang;

import cn.com.lxsoft.bdasphone.database.greendao.DanWeiDao;
import cn.com.lxsoft.bdasphone.database.greendao.LuXianDao;
import cn.com.lxsoft.bdasphone.database.greendao.QiaoLiangDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig danWeiDaoConfig;
    private final DaoConfig luXianDaoConfig;
    private final DaoConfig qiaoLiangDaoConfig;

    private final DanWeiDao danWeiDao;
    private final LuXianDao luXianDao;
    private final QiaoLiangDao qiaoLiangDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        danWeiDaoConfig = daoConfigMap.get(DanWeiDao.class).clone();
        danWeiDaoConfig.initIdentityScope(type);

        luXianDaoConfig = daoConfigMap.get(LuXianDao.class).clone();
        luXianDaoConfig.initIdentityScope(type);

        qiaoLiangDaoConfig = daoConfigMap.get(QiaoLiangDao.class).clone();
        qiaoLiangDaoConfig.initIdentityScope(type);

        danWeiDao = new DanWeiDao(danWeiDaoConfig, this);
        luXianDao = new LuXianDao(luXianDaoConfig, this);
        qiaoLiangDao = new QiaoLiangDao(qiaoLiangDaoConfig, this);

        registerDao(DanWei.class, danWeiDao);
        registerDao(LuXian.class, luXianDao);
        registerDao(QiaoLiang.class, qiaoLiangDao);
    }
    
    public void clear() {
        danWeiDaoConfig.clearIdentityScope();
        luXianDaoConfig.clearIdentityScope();
        qiaoLiangDaoConfig.clearIdentityScope();
    }

    public DanWeiDao getDanWeiDao() {
        return danWeiDao;
    }

    public LuXianDao getLuXianDao() {
        return luXianDao;
    }

    public QiaoLiangDao getQiaoLiangDao() {
        return qiaoLiangDao;
    }

}
